// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqlskoaqsyxrzyowjvrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxbHNrb2Fxc3l4cnp5b3dqdnJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NjQ4MDMsImV4cCI6MjA2MjM0MDgwM30.7avriUQDTNSDhL1QmVAkkhhuxamndxs4Lr8ZnUeN_TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);